name: LCA-H2

dependencies:
  - python=3.9
  - pip
  - numpy
  - pyomo
  - pandas
  - statsmodels
  - matplotlib
  - xlrd
  - openpyxl
  - ipywidgets
  - traitlets
  - scipy
  - tensorflow
  - keras
  - scikit-learn
  - termcolor
